package tribalj;
// Generated Oct 12, 2015 10:41:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Stations generated by hbm2java
 */
public class Stations  implements java.io.Serializable {


     private Long stId;
     private String name;
     private Double lat;
     private Double long_;
     private Double alt;
     private String hardware;
     private String software;
     private Set systems = new HashSet(0);
     private Set datas = new HashSet(0);

    public Stations() {
    }

	
    public Stations(String name) {
        this.name = name;
    }
    public Stations(String name, Double lat, Double long_, Double alt, String hardware, String software, Set systems, Set datas) {
       this.name = name;
       this.lat = lat;
       this.long_ = long_;
       this.alt = alt;
       this.hardware = hardware;
       this.software = software;
       this.systems = systems;
       this.datas = datas;
    }
   
    public Long getStId() {
        return this.stId;
    }
    
    public void setStId(Long stId) {
        this.stId = stId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Double getLat() {
        return this.lat;
    }
    
    public void setLat(Double lat) {
        this.lat = lat;
    }
    public Double getLong_() {
        return this.long_;
    }
    
    public void setLong_(Double long_) {
        this.long_ = long_;
    }
    public Double getAlt() {
        return this.alt;
    }
    
    public void setAlt(Double alt) {
        this.alt = alt;
    }
    public String getHardware() {
        return this.hardware;
    }
    
    public void setHardware(String hardware) {
        this.hardware = hardware;
    }
    public String getSoftware() {
        return this.software;
    }
    
    public void setSoftware(String software) {
        this.software = software;
    }
    public Set getSystems() {
        return this.systems;
    }
    
    public void setSystems(Set systems) {
        this.systems = systems;
    }
    public Set getDatas() {
        return this.datas;
    }
    
    public void setDatas(Set datas) {
        this.datas = datas;
    }




}


