package tribalj;
// Generated Oct 12, 2015 10:41:39 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * System generated by hbm2java
 */
public class System  implements java.io.Serializable {


     private Long id;
     private Stations stations;
     private Date time;
     private Double temp;
     private Double voltage;
     private Double mem;
     private Double freeMem;
     private Double cashMem;

    public System() {
    }

	
    public System(Stations stations, Date time) {
        this.stations = stations;
        this.time = time;
    }
    public System(Stations stations, Date time, Double temp, Double voltage, Double mem, Double freeMem, Double cashMem) {
       this.stations = stations;
       this.time = time;
       this.temp = temp;
       this.voltage = voltage;
       this.mem = mem;
       this.freeMem = freeMem;
       this.cashMem = cashMem;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Stations getStations() {
        return this.stations;
    }
    
    public void setStations(Stations stations) {
        this.stations = stations;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public Double getTemp() {
        return this.temp;
    }
    
    public void setTemp(Double temp) {
        this.temp = temp;
    }
    public Double getVoltage() {
        return this.voltage;
    }
    
    public void setVoltage(Double voltage) {
        this.voltage = voltage;
    }
    public Double getMem() {
        return this.mem;
    }
    
    public void setMem(Double mem) {
        this.mem = mem;
    }
    public Double getFreeMem() {
        return this.freeMem;
    }
    
    public void setFreeMem(Double freeMem) {
        this.freeMem = freeMem;
    }
    public Double getCashMem() {
        return this.cashMem;
    }
    
    public void setCashMem(Double cashMem) {
        this.cashMem = cashMem;
    }




}


